### ISSUE TITLE
棒磁石が動かない

### ISSUE THREAD

**Issue by tatsuro-ueda** [feel-physics/HoloMagnet3#3]
最初のIntroductionシーンの次のCompass_Oneシーンで、棒磁石が動かない

以下のようなエラーが出ると、棒磁石が動かなくなる

```
NullReferenceException: Object reference not set to an instance of an object
HoloToolkit.Unity.InputModule.SpeechInputHandler.OnEnable () (at Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/SpeechInputHandler.cs:48)

NullReferenceException: Object reference not set to an instance of an object
HoloToolkit.Unity.InputModule.GamePadHandlerBase.OnEnable () (at Assets/HoloToolkit/Input/Scripts/GamePad/GamePadHandlerBase.cs:17)
```

該当行をコメントアウトすると棒磁石がまったく動かなくなる

**Comment by the6th** [comment]
@tatsuro-ueda 

現状、SpeechInputHandler（音声入力）　と　GamePadHandlerBase（箱コンでの操作）は、アプリ内で利用しているのですか？
ぱっと見、見つけられなかったのですが、不要なら削除する方向で調整しようかと考えているのですが

**Comment by tatsuro-ueda** [comment]
ありがとうございます。その方向でよろしくお願いします。

**Comment by the6th** [comment]
了解です。これも調整します。また、後日解説しますが、
SpeechInputHandlerが現状、SetGlobalListenerを利用するためだけに 付与されてる感じなので
その機能を別のスクリプトに動かして

SpeechInputHandler/GamePadHandlerBaseのGlobalListeneraは使わないようにします。

**Comment by tatsuro-ueda** [comment]
ありがとうございます。その方向でよろしくお願いします。
