### ISSUE TITLE
シェーダの問題

### ISSUE THREAD

**Issue by tatsuro-ueda** [feel-physics/HoloMagnet3#4]

**Comment by tatsuro-ueda** [comment]
[該当シェーダ](https://github.com/feel-physics/HoloMagnet3/blob/master/Assets/HoloMagnet3/Resources/Compass180509/MyDirectionShader2.shader)

**Comment by tatsuro-ueda** [comment]
- MRTKのシェーダを使っていないため光が出てしまっている
- 磁力の影響がないときに真っ黒（HoloLens上では見えない）ようにしたい

**Comment by the6th** [comment]
![magneti_shader](https://user-images.githubusercontent.com/24910354/57344362-eb112500-7181-11e9-8213-bd19909088b2.gif)

こんな感じで、消えるようにしました。
消えるタイミングは0.02などべた書きにしちゃっています。
上記commitで

**Comment by tatsuro-ueda** [comment]
ありがとうございます。現状ちょっと明るすぎますが、それはこちらで調整します。
