### ISSUE TITLE
[質問]ScriptingBackEndに.NET4.6

### ISSUE THREAD

**Issue by the6th** [feel-physics/HoloMagnet3#5]
Scripting Backendに.NET4.6が使われているのは、何か理由があるのでしょうか？

![image](https://user-images.githubusercontent.com/24910354/57265366-5ab7df00-70b2-11e9-8eb7-af80cab05927.png)

元の、3.5に変えてみたところ、ぱっと見エラーは出てない感じですが、
4.6だと、VisualStudioが環境によっては追加の.netインストールが必要になるので、
他の人が利用するときにつまずく原因になりそうだなと。

3.5に変えてしまっても良いのでしょうか？

**Comment by tatsuro-ueda** [comment]
ご指摘ありがとうございます。おそらく昔Linqを使うために入れたものだと思います。現状では必要ありません。変えてしまって構いません。

**Comment by the6th** [comment]
了解です。そうします。　
現在 the6th　というbranchで一部手を入れ始めています。
